# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc62ce69520026a685f5edf53fc0c060bac4e5db2fcf31f6f4b3ef0ee03b192597f15bbb9aba094307237efee5dd910e0e5da85c34b429555c40489143dffb61

test:
  secret_key_base: 39a756a7728e58ca7156ab7159ccceb7ea163911271e1a48066def775fdad57b9d9dbc679464778117d555b76f60a645095e17296df0c170cfb9b7dc27111a06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
